### ISSUE TITLE
Please show an example using a streaming result?

### ISSUE THREAD

**Issue by chrispsommers** [kmturley/angular-nest-grpc#4]
Hi, could you possibly show us an example  of how to implement an angular client rpc fetch where the return value is a `stream` type?  I found something similar at https://github.com/improbable-eng/grpc-web/blob/master/client/grpc-web-react-example/ts/src/index.ts but am not sure how to relate that solution to your framework. Thanks!

**Comment by kmturley** [comment]
Interesting, have not used that approach yet. To do it I think we would need to compare the files in three places:

Models:
[hero.proto](https://github.com/kmturley/angular-nest-grpc/blob/master/backend/src/hero/hero.proto)
[book_service.proto](https://github.com/improbable-eng/grpc-web/blob/master/client/grpc-web-react-example/proto/examplecom/library/book_service.proto)

Backend:
[hero.controller.ts](https://github.com/kmturley/angular-nest-grpc/blob/master/backend/src/hero/hero.controller.ts#L53)
[book_service.pb.go](https://github.com/improbable-eng/grpc-web/blob/master/client/grpc-web-react-example/go/_proto/examplecom/library/book_service.pb.go#L140)

Frontend:
[api.service.ts](https://github.com/kmturley/angular-nest-grpc/blob/master/frontend/src/app/api.service.ts#L16)
[index.ts](https://github.com/improbable-eng/grpc-web/blob/master/client/grpc-web-react-example/ts/src/index.ts#L29)

If I have more time I can definitely look at this!

**Comment by chrispsommers** [comment]
Hi  Kevin, thanks for responding! After much trial-and-error (because I'm also an angular/TS/JS newbie) I was able to get the following snippet working. The details of my service aren't important but the semantics work. The commented out portions fail to compile, I couldn't get the `grpcWeb` symbols to resolve (Stats, Error). The main thing is, I got the promise to work and callers of this get the expected data from the streaming service. Hope this is useful!
```
import { Injectable } from '@angular/core';
import * as grpcWeb from 'grpc-web';
// import my service protobuf files...
  getServiceInfo() {
    return new Promise((resolve, reject) => {
      console.log('ServiceInfoService.Read');
      const req = new ReadRequest();
      const stream = this.client.read(req);
      stream.on('data', (response: ReadResponse) => {
        resolve(this.serviceInfo)
      });
      // stream.on('status', (status: grpcWeb.Status) => {
      //   if (status.metadata) {
      //     console.log('Received metadata');
      //     console.log(status.metadata);
      //   }
      // });
      // stream.on('error', (err: grpcWeb.Error) => {
      //   console.log(
      //       'Error code: ' + err.code + ' "' + err.message + '"');
      // });
      stream.on('end', () => {
        console.log('stream end signal received');
      });
    });
  }
```

**Comment by kmturley** [comment]
Looks like NestJS has released a fix for this 6.3.0:
https://github.com/nestjs/nest/releases/tag/v6.3.0

So I can test using the new version. Here are the two threads talking about the fix:
https://github.com/nestjs/nest/issues/1286
https://github.com/nestjs/nest/pull/1568

**Comment by kmturley** [comment]
@chrispsommers Check out the new version for examples on using streaming methods:
https://github.com/kmturley/angular-nest-grpc/pull/6/files

**Comment by chrispsommers** [comment]
@kmturley Hey that's totally cool! I'm sure a lot of people can  learn from this. Your initial project got me started on a great path, now this adds another nice capability. Thanks for being so responsive!
